# Floresta Node Configuration for ANCHOR
# https://github.com/vinteumorg/Floresta
# Network is set via CLI: --network regtest

[node]
# Bind RPC to all interfaces for Docker networking
rpc_bind = "0.0.0.0:18442"

[electrum]
# Bind Electrum to all interfaces
address = "0.0.0.0:20001"

[rpc]
# RPC authentication
username = "anchor"
password = "anchor"
